server:
  port: 80
  context-path: /api
mongo:
  ip: "45.78.8.74"
  port: "29762"
  user: "chenanyi"
  user_pw: "nishengri"
  root_pw: "6UryW29kxuvp"
logging:
  file: ./logs/test.log
  level:
    root:
      INFO
spring:
  data:
    mongodb:
      host: 45.78.8.74
      port: 27017
      username: chenanyi
      password: nishengri
      database: farm
      authenticationDatabase: farm
mobileverify:
  messageUrl:
    http://gw.api.taobao.com/router/rest
  appKey:
    23597883
  appSecret:
    bab58118a48b72e17fab0809016316ca
  validity:
    5
  tempId:
    SMS_40040034
  signName:
    陈安一