server:
  port: 80
  context-path: /api
mongo:
  ip: 45.78.8.74
  port: 29762
  user: chenanyi
  user_pw: nishengri
  root_pw: 6UryW29kxuvp
mobileverify:
  appKey: "08c53213c0b3e974a7ea47929b88ca05"
  appSecret: "3b1445feed4b"
logging:
  file: ./logs/test.log
  level:
    root:
      INFO
spring:
  data:
    mongodb:
      host: 45.78.8.74
      port: 27017
      username: chenanyi
      password: nishengri
      database: farm
      authenticationDatabase: farm
