server:
  port: 8080
  context-path: /api
mongo:
  ip: 45.78.8.74
  port: 29762
  user: chenanyi
  user_pw: nishengri
  root_pw: 6UryW29kxuvp
spring:
  data:
    mongodb:
      host: 45.78.8.74
      port: 27017
      username: chenanyi
      password: nishengri
      database: users
      authenticationDatabase: users