server:
  port: 80
  context-path: /api
mongo:
  ip: "45.78.8.74"
  port: "29762"
  user: "chenanyi"
  user_pw: "nishengri"
  root_pw: "6UryW29kxuvp"
push:
  appKey: "453872f68d81d42ff84c2ad5"
  masterSecret: "0c52d917fd9cc3661903f771"
logging:
  file: ./logs/test.log
  level:
    root:
      INFO
spring:
  data:
    mongodb:
      host: 45.78.8.74
      port: 27017
      username: chenanyi
      password: nishengri
      database: farm
      authenticationDatabase: farm

  redis:
    database: 0
    host: 45.78.8.74
    port: 6379
    password: nishengri
    pool:
      max-active: 500
      max-idle: 20
      max-wait: 1000
      min-idle: 0
    timeout: 2000
mobileverify:
  messageUrl: http://gw.api.taobao.com/router/rest
  appKey: 23597883
  appSecret: bab58118a48b72e17fab0809016316ca
  validity: 5
  tempId: SMS_40040034
  signName: 陈安一