server:
  port: 8282
  context-path: /api
aes:
  key: asdqwe21e23896cd
  iv: 18669704568cay88
push:
  appKey: "453872f68d81d42ff84c2ad5" #"4056c2f4d32b4dbac6dc147c"
  masterSecret: "0c52d917fd9cc3661903f771" #"4aacc8eee6cf8127d4c777f4"
logging:
  file: ./logs/test.log
  level:
    root:
      INFO
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: chenanyi
      password: nishengri
      database: farm
      authenticationDatabase: farm
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 20 # 连接池中的最大空闲连接
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 30000 # 连接超时时间（毫秒）
redisconfig:
  ip: 127.0.0.1
fileupload:
  ak: "Wk5ul8bR8jk4td3zVYlvlK1oyivSFRbbmAW__TPp" #"u93z34EKsgIVJyoxVutBXLb6MyxDbGyhhk5XKxQP"
  sk: "lV2pJws51KV3grP6debWFzwtigYp67tFwdH3wJl6" #"ifUcr7mBAAkkyk9pa2ZiY8pCtK-I7IGTfl_HXxGJ"
  bname: "heituimage"
  url: "http://oruhxludd.bkt.clouddn.com/" #"http://ok7ng9gi2.bkt.clouddn.com/"
mobileverify:
  messageUrl:
    http://gw.api.taobao.com/router/rest
  appKey:
    23597883
  appSecret:
    bab58118a48b72e17fab0809016316ca
  validity:
    5
  tempId:
    SMS_40040034
  signName:
    陈安一